// Footnotes maintenance (footnotes.js) on the existing filing footnote store; generated by the existing generator.
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { DOMParser } from '@xmldom/xmldom';
import { authority, q } from './helpers.mjs';
import { baseSession } from './fixtures.mjs';
import { Session } from './session.js';
import { generateInstance } from './generator.js';
import { listFootnotes, footnotesOf, addFootnote, updateFootnoteText, linkFootnote, unlinkFootnote, removeFootnote } from './footnotes.js';

globalThis.DOMParser ||= DOMParser;
const A = authority();

test('add / attach / edit / unlink / delete; ids stay unique after a delete', () => {
  const s = baseSession();
  s.setValue(q('OtherIncome'), 'CY', '100');
  const k = s.getValue(q('OtherIncome'), 'CY').key;
  const a = addFootnote(s.filing, 'First note', [k]);
  const b = addFootnote(s.filing, 'Second note', [k]);
  assert.deepEqual(footnotesOf(s.filing, k), [a, b]);
  removeFootnote(s.filing, a);
  const c = addFootnote(s.filing, 'Third note', [k]);
  assert.notEqual(c, b, 'new id does not overwrite an existing footnote');
  assert.equal(listFootnotes(s.filing).length, 2);
  updateFootnoteText(s.filing, b, 'Second note, edited');
  assert.equal(s.filing.footnotes.get(b).text, 'Second note, edited');
  unlinkFootnote(s.filing, c, k);
  assert.deepEqual(footnotesOf(s.filing, k), [b]);
  linkFootnote(s.filing, c, k);
  assert.deepEqual(footnotesOf(s.filing, k), [b, c]);
  assert.throws(() => addFootnote(s.filing, '  ', [k]), /empty/);
  assert.throws(() => addFootnote(s.filing, 'x', ['no#such#cell']), /has a value/);
});

test('generated as an XBRL footnote link on the fact, and survives export → import', () => {
  const s = baseSession();
  s.setValue(q('OtherIncome'), 'CY', '100');
  const k = s.getValue(q('OtherIncome'), 'CY').key;
  addFootnote(s.filing, 'Includes interest & dividends <net>', [k]);
  addFootnote(s.filing, 'Orphan note — no cell', []);
  const { xml } = generateInstance(A, s.filing);
  assert.match(xml, /<link:footnote [^>]*xml:lang="en">Includes interest &amp; dividends &lt;net&gt;<\/link:footnote>/);
  assert.match(xml, /<in-gaap:OtherIncome [^>]*id="F\d+"/);
  assert.match(xml, /xlink:arcrole="http:\/\/www.xbrl.org\/2003\/arcrole\/fact-footnote"/);
  assert.ok(!xml.includes('Orphan note'), 'a footnote without a generated fact is not written');
  const t = new Session(A);
  t.importXml(xml, { yearMode: 'both' });
  const fk = t.getValue(q('OtherIncome'), 'CY').key;
  assert.deepEqual(listFootnotes(t.filing).map((x) => x.text), ['Includes interest & dividends <net>']);
  assert.equal(footnotesOf(t.filing, fk).length, 1);
});

test('MCA-validated FILING-B footnotes are listed with their cells', () => {
  const s = new Session(A);
  s.importXml(readFileSync(new URL('golden-FILING-B_2024-25.xml', import.meta.url), 'utf8'), { yearMode: 'both' });
  const l = listFootnotes(s.filing);
  assert.equal(l.length, 3);
  assert.ok(l.every((x) => x.facts.length >= 1 && x.text.trim()));
});
