// The single authoritative XBRL instance generator.
// Deterministic output: contexts, units and facts are emitted in a stable order with stable ids.
// No precision, no scale, no extensions; prescribed schemaRef and CIN scheme from the authority.
import { unitDef } from './units.js';
import { scopeOf } from './periods.js';

const NS = {
  xbrli: 'http://www.xbrl.org/2003/instance',
  link: 'http://www.xbrl.org/2003/linkbase',
  xlink: 'http://www.w3.org/1999/xlink',
  xbrldi: 'http://xbrl.org/2006/xbrldi',
  iso4217: 'http://www.xbrl.org/2003/iso4217',
  xsi: 'http://www.w3.org/2001/XMLSchema-instance',
};

export const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

// FNV-1a 32-bit, hex — deterministic short hash for context ids
export function fnv(str) {
  let h = 0x811c9dc5;
  for (let i = 0; i < str.length; i++) { h ^= str.charCodeAt(i); h = Math.imul(h, 0x01000193) >>> 0; }
  return h.toString(16).padStart(8, '0');
}

let _order = null;
function conceptOrder(A) {
  if (_order && _order.A === A) return _order.map;
  const map = new Map();
  let i = 0;
  for (const e of A.elrs) {
    const walk = (q) => { if (!map.has(q)) map.set(q, i++); for (const a of A.presentationChildren(e.uri, q)) walk(a.to); };
    for (const r of e.roots) walk(r);
  }
  _order = { A, map };
  return map;
}

function periodBaseId(periods, p) {
  const s = scopeOf(periods, p);
  const y = (d) => d.slice(0, 4);
  if (p.type === 'duration') {
    if (s === 'CY' || s === 'PY') return `D${y(p.end)}`;
    return `D${p.start.replace(/-/g, '')}_${p.end.replace(/-/g, '')}`;
  }
  if (s === 'CY' || s === 'PY' || s === 'PYO') return `I${y(p.date)}`;
  return `I${p.date.replace(/-/g, '')}`;
}

export function buildContexts(filing, facts) {
  const map = new Map(); // internal key -> {id, period, dims}
  const used = new Set();
  const keyOf = (f) => `${f.period.type === 'instant' ? 'I:' + f.period.date : 'D:' + f.period.start + ':' + f.period.end}#${f.dims.map((d) => `${d.axis}=${d.member ?? JSON.stringify(d.typed)}`).join('|')}`;
  const sorted = [...new Map(facts.map((f) => [keyOf(f), f])).entries()].sort(([a], [b]) => a.localeCompare(b));
  for (const [k, f] of sorted) {
    let id = periodBaseId(filing.meta.periods, f.period);
    if (f.dims.length) id += '_' + fnv(f.dims.map((d) => `${d.axis}=${d.member ?? JSON.stringify(d.typed)}`).join('|'));
    let final = id, n = 2;
    while (used.has(final)) final = `${id}_${n++}`; // collision-safe
    used.add(final);
    map.set(k, { id: final, period: f.period, dims: f.dims });
  }
  return { map, keyOf };
}

export function generateInstance(A, filing, facts = filing.all()) {
  const order = conceptOrder(A);
  const { map: ctxMap, keyOf } = buildContexts(filing, facts);
  const usedUnits = new Set(facts.filter((f) => f.unit && !f.nil).map((f) => f.unit));
  for (const f of facts) if (f.unit && f.nil) usedUnits.add(f.unit);
  const prefixes = new Set(facts.map((f) => f.concept.split(':')[0]));
  for (const f of facts) for (const d of f.dims) { prefixes.add(d.axis.split(':')[0]); if (d.member) prefixes.add(d.member.split(':')[0]); else prefixes.add(A.typedDomain(d.axis).split(':')[0]); }
  const sortedFacts = facts.slice().sort((a, b) => (order.get(a.concept) ?? 1e9) - (order.get(b.concept) ?? 1e9) || a.concept.localeCompare(b.concept) || ctxMap.get(keyOf(a)).id.localeCompare(ctxMap.get(keyOf(b)).id));

  // fact ids only where needed (footnotes)
  const footnoted = new Map();
  let fid = 1;
  const factIds = new Map();
  for (const fn of filing.footnotes.values()) for (const k of fn.factKeys) if (!factIds.has(k) && facts.some((f) => f.key === k)) factIds.set(k, null);
  for (const f of sortedFacts) if (factIds.has(f.key)) factIds.set(f.key, `F${fid++}`);

  const L = [];
  L.push('<?xml version="1.0" encoding="UTF-8"?>');
  // identifies the tool build that produced the file (a stale cached page shows an old build id)
  L.push(`<!-- Generated by C&amp;I XBRL Studio build ${String(globalThis.MCA_BUILD_ID || 'dev').replace(/[^\w.-]/g, '')} -->`);
  const nsDecl = [
    `xmlns:xbrli="${NS.xbrli}"`, `xmlns:link="${NS.link}"`, `xmlns:xlink="${NS.xlink}"`, `xmlns:xbrldi="${NS.xbrldi}"`,
    `xmlns:iso4217="${NS.iso4217}"`, `xmlns:xsi="${NS.xsi}"`,
    ...[...prefixes].sort().map((p) => `xmlns:${p}="${A.namespaces[p]}"`),
  ];
  L.push(`<xbrli:xbrl ${nsDecl.join(' ')}>`);
  L.push(`  <link:schemaRef xlink:type="simple" xlink:href="${esc(filing.meta.schemaRef || A.meta.schemaRef)}"/>`);
  for (const c of [...ctxMap.values()].sort((a, b) => a.id.localeCompare(b.id))) {
    L.push(`  <xbrli:context id="${c.id}">`);
    L.push(`    <xbrli:entity><xbrli:identifier scheme="${esc(A.meta.cinScheme)}">${esc(filing.meta.cin)}</xbrli:identifier></xbrli:entity>`);
    L.push(c.period.type === 'instant'
      ? `    <xbrli:period><xbrli:instant>${c.period.date}</xbrli:instant></xbrli:period>`
      : `    <xbrli:period><xbrli:startDate>${c.period.start}</xbrli:startDate><xbrli:endDate>${c.period.end}</xbrli:endDate></xbrli:period>`);
    if (c.dims.length) {
      L.push('    <xbrli:scenario>');
      for (const d of c.dims) {
        if (d.member) L.push(`      <xbrldi:explicitMember dimension="${d.axis}">${d.member}</xbrldi:explicitMember>`);
        else { const dom = A.typedDomain(d.axis); L.push(`      <xbrldi:typedMember dimension="${d.axis}"><${dom}>${esc(d.typed)}</${dom}></xbrldi:typedMember>`); }
      }
      L.push('    </xbrli:scenario>');
    }
    L.push('  </xbrli:context>');
  }
  for (const u of [...usedUnits].sort()) {
    const def = unitDef(u);
    if (!def) throw new Error(`Unknown unit ${u}`);
    if (def.denominator) L.push(`  <xbrli:unit id="${def.id}"><xbrli:divide><xbrli:unitNumerator><xbrli:measure>${def.numerator[0]}</xbrli:measure></xbrli:unitNumerator><xbrli:unitDenominator><xbrli:measure>${def.denominator[0]}</xbrli:measure></xbrli:unitDenominator></xbrli:divide></xbrli:unit>`);
    else L.push(`  <xbrli:unit id="${def.id}"><xbrli:measure>${def.measures[0]}</xbrli:measure></xbrli:unit>`);
  }
  for (const f of sortedFacts) {
    const ctx = ctxMap.get(keyOf(f)).id;
    const attrs = [`contextRef="${ctx}"`];
    const id = factIds.get(f.key);
    if (id) attrs.push(`id="${id}"`);
    if (A.isNumeric(f.concept)) {
      attrs.push(`unitRef="${f.unit}"`);
      if (f.nil) { attrs.push('xsi:nil="true"'); L.push(`  <${f.concept} ${attrs.join(' ')}/>`); continue; }
      attrs.push(`decimals="${f.decimals}"`);
      L.push(`  <${f.concept} ${attrs.join(' ')}>${f.value}</${f.concept}>`);
    } else {
      if (f.lang && A.langAllowed(f.concept)) attrs.push(`xml:lang="${esc(f.lang)}"`);
      if (f.nil) { attrs.push('xsi:nil="true"'); L.push(`  <${f.concept} ${attrs.join(' ')}/>`); continue; }
      L.push(`  <${f.concept} ${attrs.join(' ')}>${esc(f.value)}</${f.concept}>`);
    }
  }
  const notes = [...filing.footnotes.values()].filter((fn) => [...fn.factKeys].some((k) => factIds.get(k)) && fn.text.trim());
  if (notes.length) {
    L.push('  <link:footnoteLink xlink:type="extended" xlink:role="http://www.xbrl.org/2003/role/link">');
    for (const [k, id] of factIds) if (id) L.push(`    <link:loc xlink:type="locator" xlink:href="#${id}" xlink:label="${id}"/>`);
    for (const fn of notes) {
      L.push(`    <link:footnote xlink:type="resource" xlink:label="${fn.id}" xlink:role="http://www.xbrl.org/2003/role/footnote" xml:lang="${esc(fn.lang || 'en')}">${esc(fn.text)}</link:footnote>`);
      for (const k of fn.factKeys) { const id = factIds.get(k); if (id) L.push(`    <link:footnoteArc xlink:type="arc" xlink:arcrole="http://www.xbrl.org/2003/arcrole/fact-footnote" xlink:from="${id}" xlink:to="${fn.id}"/>`); }
    }
    L.push('  </link:footnoteLink>');
  }
  L.push('</xbrli:xbrl>');
  return { xml: L.join('\n') + '\n', contexts: [...ctxMap.values()], factIds };
}
