// MCA Validator error explainer: turns the validator's error list (Xerces schema messages and MCA messages) into
// plain-language meaning, likely cause and the fix in this tool. Pure text analysis — it does not validate anything
// and does not change the filing. Unknown messages are reported as unknown, never guessed.
//
// Background: the MCA Validator checks the instance against the taxonomy XML Schemas with Xerces. Xerces messages
// start with a constraint code from the W3C XML Schema spec ("cvc-…" = "constraint on validation contents"); the code
// names WHAT kind of rule failed, the quoted names say WHERE.

const PATTERNS = [
  {
    code: 'html', re: /Element '([^']+)' the contained HTML has the following errors:\s*(.*)$/,
    title: 'HTML inside a text block',
    meaning: (m) => `The text block ${m[1]} contains HTML that the MCA HTML schema (namespace http://www.mca.gov.in/XBRL/HTML) does not accept. The details after the colon are ordinary schema messages about that HTML (explained below).`,
    cause: 'Usually a table or formatting pasted from Word/Excel/web (colgroup, colspan, rowspan, style, width, align …) that was saved by an older build, or imported unchanged.',
    fix: 'Open the text block (Text Block button) and click Save Text: the editor rebuilds the content in the MCA subset (merged cells become empty cells, colgroup is dropped). Then Validate and generate again. The internal Validation tab reports the same constructs as errors.',
    element: (m) => m[1],
    nested: (m) => m[2].split(/;\s*/).filter(Boolean),
  },
  {
    code: 'cvc-complex-type.3.2.2', re: /cvc-complex-type\.3\.2\.2: Attribute '([^']+)' is not allowed to appear in element '([^']+)'/,
    title: 'Attribute not allowed on this element',
    meaning: (m) => `The schema of '${m[2]}' does not declare the attribute '${m[1]}'.`,
    cause: (m) => m[1] === 'xml:lang'
      ? 'xml:lang is allowed only on plain string and text-block elements. This element uses an MCA restricted type (PAN, CIN, DIN, list values …), which forbids it. Current builds never write it there — an XML that still has it came from an old (cached) copy of the tool.'
      : /^(colspan|rowspan|style|width|align|valign|border|cellpadding|cellspacing|height|lang|id|bgcolor)$/i.test(m[1])
        ? 'An HTML attribute from pasted content (Word/Excel/web). MCA-validated text blocks use only class="…".'
        : 'The element carries an attribute its schema does not define.',
    fix: (m) => m[1] === 'xml:lang'
      ? 'Check the build: the first comment line of the XML ("Generated by C&I XBRL Studio build …") must match the build shown in the tool header. If not, hard-refresh the page (Ctrl+F5 / Cmd+Shift+R), re-open the project and generate again.'
      : 'If it is inside a text block: open the text block and click Save Text. Otherwise report the element and attribute — the generator should not write it.',
    element: (m) => m[2],
  },
  {
    code: 'cvc-complex-type.2.4.a', re: /cvc-complex-type\.2\.4\.a: Invalid content was found starting with element '([^']+)'\. One of '\{?(.*?)\}?' is expected/,
    title: 'Element not allowed at this position',
    meaning: (m) => `'${shortName(m[1])}' appears where the schema expects one of: ${m[2].split(/,\s*/).map(shortName).join(', ')}.`,
    cause: (m) => /^(colgroup|col|caption)$/.test(shortName(m[1])) ? 'A Word/Excel table structure (<colgroup>/<col>/<caption>). The MCA HTML schema allows only thead/tbody/tfoot/tr inside <table>.' : 'Wrong nesting or order of elements (for HTML: a tag in a place the MCA HTML schema does not allow).',
    fix: 'Inside a text block: open it and click Save Text (the editor rebuilds the structure). In the XBRL part: report it — the generator controls element order.',
  },
  {
    code: 'cvc-complex-type.2.4.b', re: /cvc-complex-type\.2\.4\.b: The content of element '([^']+)' is not complete\. One of '\{?(.*?)\}?' is expected/,
    title: 'Required child element missing',
    meaning: (m) => `'${shortName(m[1])}' must contain one of: ${m[2].split(/,\s*/).map(shortName).join(', ')}.`,
    cause: 'An empty structure (for example an empty table row or an empty context/segment).',
    fix: 'For text blocks: remove empty tables/rows and save the text block again. Otherwise report it.',
    element: (m) => m[1],
  },
  {
    code: 'cvc-complex-type.4', re: /cvc-complex-type\.4: Attribute '([^']+)' must appear on element '([^']+)'/,
    title: 'Required attribute missing',
    meaning: (m) => `'${m[2]}' must carry the attribute '${m[1]}'.`,
    cause: 'contextRef / unitRef / decimals missing on a fact.',
    fix: 'Report it — the generator writes these attributes.',
    element: (m) => m[2],
  },
  {
    code: 'cvc-pattern-valid', re: /cvc-pattern-valid: Value '([^']*)' is not facet-valid with respect to pattern '([^']*)' for type '([^']+)'/,
    title: 'Value has the wrong format',
    meaning: (m) => `'${m[1]}' does not match the required format of type ${m[3]} (regular expression ${m[2]}).`,
    cause: 'Typing error in a coded value (PAN, CIN, DIN, SRN, ITC code, e-mail …): wrong length, lower-case letters, spaces.',
    fix: 'Find the element named in the next line (cvc-type.3.1.3) and correct the value. Letters must usually be upper case; no spaces.',
  },
  {
    code: 'cvc-enumeration-valid', re: /cvc-enumeration-valid: Value '([^']*)' is not facet-valid with respect to enumeration '\[(.*)\]'/,
    title: 'Value not in the allowed list',
    meaning: (m) => `'${m[1]}' is not one of: ${m[2]}.`,
    cause: 'A list value typed or imported with different spelling/case.',
    fix: 'Pick the value from the drop-down of the element named in the next line (cvc-type.3.1.3).',
  },
  {
    code: 'cvc-length-valid', re: /cvc-(length|minLength|maxLength)-valid: Value '([^']*)' with length = '(\d+)' is not facet-valid with respect to (?:length|minLength|maxLength) '(\d+)'/,
    title: 'Value has the wrong length',
    meaning: (m) => `'${m[2]}' has ${m[3]} characters; the type requires ${m[1] === 'length' ? 'exactly' : m[1] === 'minLength' ? 'at least' : 'at most'} ${m[4]}.`,
    cause: 'Code values with a fixed length (PAN 10, CIN 21, DIN 8 …).',
    fix: 'Correct the value of the element named in the next line (cvc-type.3.1.3).',
  },
  {
    code: 'cvc-datatype-valid', re: /cvc-datatype-valid\.1\.2\.1: '([^']*)' is not a valid value for '([^']+)'/,
    title: 'Value is not of the right data type',
    meaning: (m) => `'${m[1]}' is not a valid ${m[2]}.`,
    cause: 'Text in a number/date/boolean element (for example a comma, a space or a date in dd-mm-yyyy).',
    fix: 'Correct the value of the element named in the next line. Dates are yyyy-mm-dd; numbers without separators.',
  },
  {
    code: 'cvc-type.3.1.3', re: /cvc-type\.3\.1\.3: The value '([^']*)' of element '([^']+)' is not valid/,
    title: 'Which element has the invalid value',
    meaning: (m) => `Element '${m[2]}' has the invalid value '${m[1]}' (the reason is in the line before).`,
    cause: 'See the previous message.',
    fix: 'Go to the element and correct the value.',
    element: (m) => m[2],
  },
  {
    code: 'cvc-elt.3.1', re: /cvc-elt\.3\.1: Attribute '[^']*nil' must not appear on element '([^']+)'/,
    title: 'Element may not be nil',
    meaning: (m) => `'${m[1]}' is not nillable, but was written with xsi:nil="true".`,
    cause: 'An empty value marked as nil.', fix: 'Enter a value or remove the cell content.',
    element: (m) => m[1],
  },
  {
    code: 'cvc-elt.1', re: /cvc-elt\.1(?:\.a)?: Cannot find the declaration of element '([^']+)'/,
    title: 'Schema not found / wrong namespace',
    meaning: (m) => `The validator does not know the element '${m[1]}'.`,
    cause: 'The taxonomy schema could not be loaded (schemaRef, offline validator, wrong taxonomy version) or the root element/namespace is wrong.',
    fix: 'Check the schemaRef in General Information / import, the validator\'s internet access and the taxonomy version (C&I 2016).',
    element: (m) => m[1],
  },
  {
    code: 'cvc-id', re: /cvc-id\.(\d): (.*)$/,
    title: 'Duplicate or missing id',
    meaning: (m) => m[2],
    cause: 'Two contexts/units/facts with the same id, or a reference to a missing id.',
    fix: 'Report it with the id named in the message.',
  },
];
const shortName = (s) => String(s).replace(/^".*?":/, '').replace(/^\{?[^}]*\}/, '').replace(/^"|"$/g, '');

/**
 * @param {string} text  the MCA Validator error list as copied from the validator / error file
 * @param {{ qnameOfLocal?: (local: string) => string|null, label?: (q: string) => string }} [A] taxonomy access
 * @returns {Array<{ n: number|null, raw: string, code: string, title: string, meaning: string, cause: string, fix: string, element: string|null, concept: string|null, label: string|null, details: object[] }>}
 */
export function explainMcaErrors(text, A = null) {
  const lines = String(text || '').split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
  const out = [];
  for (const line of lines) {
    const nm = /^(\d+)\)\s*(.*)$/.exec(line);
    const body = nm ? nm[2] : line;
    if (!nm && out.length === 0 && !/cvc-|Element '|error/i.test(body)) continue;
    if (/^NOTE:|^You should convert|^However the warning/i.test(body)) continue;
    out.push(explainOne(body, nm ? Number(nm[1]) : null, A));
  }
  // cvc-type.3.1.3 names the element for the facet error before it
  for (let i = 1; i < out.length; i++) if (out[i].code === 'cvc-type.3.1.3' && !out[i - 1].element) Object.assign(out[i - 1], { element: out[i].element, concept: out[i].concept, label: out[i].label });
  return out;
}

function explainOne(body, n, A) {
  for (const p of PATTERNS) {
    const m = p.re.exec(body);
    if (!m) continue;
    const v = (x) => (typeof x === 'function' ? x(m) : x);
    const element = p.element ? p.element(m) : null;
    const concept = element ? resolve(element, A) : null;
    return {
      n, raw: body, code: p.code, title: p.title, meaning: v(p.meaning), cause: v(p.cause), fix: v(p.fix), element, concept,
      label: concept && A?.label ? A.label(concept) : null,
      details: p.nested ? p.nested(m).map((d) => explainOne(d, null, null)) : [],
    };
  }
  const cvc = /\b(cvc-[\w.-]+)/.exec(body);
  return {
    n, raw: body, code: cvc ? cvc[1] : 'unknown', title: cvc ? 'Schema validation message (not in the explainer list)' : 'MCA message (not a schema code)',
    meaning: cvc ? `A W3C XML Schema constraint (${cvc[1]}) failed. The quoted names in the message are the element/attribute concerned.` : 'This is not a standard schema message; it usually comes from an MCA business rule or the MCA HTML/PDF checks.',
    cause: 'Not classified automatically.',
    fix: cvc ? `Search the web for "${cvc[1]}" (W3C XML Schema Part 1, Appendix C lists every code). Find the quoted element in the XML and compare with the taxonomy.` : 'Look for the element or rule name in the message, check it on the Validation tab and Rule coverage tab of this tool, and in the MCA business rules sheet.',
    element: null, concept: null, label: null, details: [],
  };
}

function resolve(element, A) {
  if (!A) return null;
  if (element.includes(':')) return A.concept?.(element) ? element : null;
  try { return A.qnameOfLocal?.(element) || null; } catch { return null; }
}
